/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */



/**
 *
 * @author xrlei
 */
public class GUI extends javax.swing.JFrame {

    // Declare master list to show all reports
    private final ReportList masterList;
    private final ReportStack priorityStack;
    private final ReportQueue priorityQueue;

    public GUI() {
        masterList = new ReportList();
        priorityStack = new ReportStack();
        priorityQueue = new ReportQueue();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        addBTN = new javax.swing.JButton();
        rmvBTN = new javax.swing.JButton();
        dltBTN = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        locField = new javax.swing.JTextField();
        typeField = new javax.swing.JTextField();
        priField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        showBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        updBTN = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayArea.setColumns(20);
        displayArea.setRows(5);
        jScrollPane1.setViewportView(displayArea);

        addBTN.setText("Add");
        addBTN.addActionListener(this::addBTNActionPerformed);

        rmvBTN.setText("Remove");
        rmvBTN.addActionListener(this::rmvBTNActionPerformed);

        dltBTN.setText("Delete");
        dltBTN.addActionListener(this::dltBTNActionPerformed);

        typeField.addActionListener(this::typeFieldActionPerformed);

        priField.addActionListener(this::priFieldActionPerformed);

        jLabel1.setText("Report ID");

        jLabel2.setText("Location");

        jLabel3.setText("Type");

        jLabel4.setText("Priority");

        showBTN.setText("Show");
        showBTN.addActionListener(this::showBTNActionPerformed);

        clearBTN.setText("Clear");
        clearBTN.addActionListener(this::clearBTNActionPerformed);

        updBTN.setText("Update");
        updBTN.addActionListener(this::updBTNActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addBTN)
                            .addComponent(updBTN))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rmvBTN)
                            .addComponent(dltBTN))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showBTN)
                            .addComponent(clearBTN)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 45, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rmvBTN)
                                .addComponent(showBTN)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dltBTN)
                            .addComponent(clearBTN)
                            .addComponent(updBTN))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(priField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>

    private void priFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // No action needed
    }

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String id = idField.getText().trim();
            String loc = locField.getText().trim();
            String type = typeField.getText().trim();
            int pri = Integer.parseInt(priField.getText().trim());

            WasteMain newReport = new WasteMain(id, loc, type, pri);

            // Sorting to stack or queue based on priority
            // 4 or lower goes to stack (higher urgency), else it goes to queue
            if (pri <= 4) {
                priorityStack.push(newReport);
                javax.swing.JOptionPane.showMessageDialog(this, "Added to Priority Stack");
            } else {
                priorityQueue.push(newReport);
                javax.swing.JOptionPane.showMessageDialog(this, "Added to Priority");
            }

            // Add new report to master list and update display
            masterList.addReport(newReport);
            displayArea.setText(masterList.getAllReports());

            // Clear input fields
            idField.setText("");
            locField.setText("");
            typeField.setText("");
            priField.setText("");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Priority must be a valid number!");
        }
    }

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // No action needed
    }

    private void showBTNActionPerformed(java.awt.event.ActionEvent evt) {
        displayArea.setText(masterList.getAllReports());
    }

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {
        idField.setText("");
        locField.setText("");
        typeField.setText("");
        priField.setText("");
        displayArea.setText("");
    }

    private void dltBTNActionPerformed(java.awt.event.ActionEvent evt) {
        String idToDelete = idField.getText().trim();
        if (idToDelete.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter report id to delete.");
            return;
        }

        boolean success = masterList.deleteByID(idToDelete);
        if (success) {
            displayArea.setText("Report " + idToDelete + " deleted\n" + masterList.getAllReports());
            idField.setText("");
            locField.setText("");
        } else {
            displayArea.setText("Cannot find Report ID: " + idToDelete);
        }
    }

    private void rmvBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // Remove next report based on urgency
        WasteMain removed = null;

        if (!priorityStack.isEmpty()) {
            removed = priorityStack.pop();
        } else if (!priorityQueue.isEmpty()) {
            removed = priorityQueue.pop();
        }

        if (removed != null) {
            masterList.deleteByID(removed.getReportID());
            displayArea.setText("Removed: " + removed.getReportID() + "\n" + masterList.getAllReports());
        } else {
            displayArea.setText("No reports available to remove.");
        }
    }

    private void updBTNActionPerformed(java.awt.event.ActionEvent evt) {
        // Updates a report by ReportID
        //Sorts after update to suitable arae
        String id = idField.getText().trim();
        WasteMain report = masterList.searchByID(id);
        if (report != null) {
            try {
                int newPri = Integer.parseInt(priField.getText().trim());
                report.setLocation(locField.getText().trim());
                report.setType(typeField.getText().trim());
                report.setPriority(newPri);

                // When priority is high enough it goes to the correct queue system
                if (newPri <= 4) {
                    priorityStack.push(report);
                } else {
                    priorityQueue.push(report);
                }

                displayArea.setText("Report " + id + " updated. \n" + masterList.getAllReports());
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Priority must be a valid number!");
            }
        } else {
            displayArea.setText("ID not found.");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JButton dltBTN;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField locField;
    private javax.swing.JTextField priField;
    private javax.swing.JButton rmvBTN;
    private javax.swing.JButton showBTN;
    private javax.swing.JTextField typeField;
    private javax.swing.JButton updBTN;
    // End of variables declaration
}


